name: Swift

on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]

jobs:
    build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  xcodebuild test -project TestGitActions.xcodeproj -scheme TestGitActions -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' build test
